# Generated by Django 5.1.4 on 2025-02-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('square_api', 'Credit Card/Debit Card (Online)'), ('cash', 'In-Person Cash Payment'), ('other', 'Other Payment Method'), ('paypal', 'PayPal Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)'), ('venmo', 'Venmo Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)'), ('cashapp', 'Cash App Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)'), ('zelle', 'Zelle Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)')], default='other'),
        ),
    ]
