# Generated by Django 5.1.12 on 2026-01-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_alter_payment_method'),
        ('payments', '0024_purchasedproduct_created_at_and_more'),
    ]

    operations = [
    ]
