# Generated by Django 5.1.12 on 2026-01-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0025_merge_20260115_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("square_api", "Credit Card/Debit Card (Online)"),
                    ("zelle", "Zelle Payment"),
                    ("cash", "In-Person Cash Payment"),
                    ("other", "Other Payment Method"),
                    ("paypal", "PayPal Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)"),
                    ("venmo", "Venmo Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)"),
                    (
                        "cashapp",
                        "Cash App Payment (LEGACY - DO NOT USE FOR NEW PAYMENTS)",
                    ),
                ],
                default="other",
            ),
        ),
    ]
